---

- name: install apache on rhel
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == 'RedHat'

- name: install apache on suse
  zypper:
    name: httpd
    state: present
  when: ansible_os_family == 'Suse'

- name: start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Check if firewalld is running
  shell: systemctl is-active firewalld
  register: firewall_status
  ignore_errors: true

- name: Open firewall ports for httpd
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true
  when: firewall_status.stdout == 'active'

- name: configure web content
  template: 
    dest: /var/www/html/index.html 
    src: index.html.j2
  notify:
    - restart httpd

- name: downgrade sudo to test insights
  yum:
    name: sudo-1.8.6p7-21.el7_3.x86_64
    state: present
    allow_downgrade: true
  when: ansible_os_family == 'RedHat'

