---

- name: include rhel apache
  include_tasks: rhel_apache.yml
  when: ansible_os_family == 'RedHat'

- name: include suse apache
  include_tasks: suse_apache.yml
  when: ansible_os_family == 'Suse'
